### PR TITLE
optional SASS

### PR DESCRIPTION
**Pull request by bahtou**
This plugin doesn't work on SASS files.

Added an option `includeSASS` to the plugin options and tweaked the config file.

Take a look. Let me know what you think.

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks! I’m away from a computer for a few days, but will take a look at this once I’m back.

**Comment by m-allanson** [comment]
Thanks @bahtou! I'm not set up to test this locally, so I've added you as a contributor in case you want to make other changes.

**Comment by m-allanson** [comment]
Published as v0.0.5

**Comment by bahtou** [comment]
Thank you 🍰

**Pull request merged**
